import type { CatalogGame } from './types';

/**
 * A small offline slice of the BGG catalog.
 *
 * It backs the fixture provider (used when BGG_ENABLED=false, in tests, and in
 * the e2e suite) and the database seed, so the demo scenario is identical
 * whether or not the machine has network access. The numbers are real BGG
 * values rounded to one or two decimals.
 */
export const FIXTURE_GAMES: CatalogGame[] = [
  {
    bggId: 13,
    name: 'CATAN',
    yearPublished: 1995,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 3,
    maxPlayers: 4,
    playingTime: 120,
    minPlayTime: 60,
    maxPlayTime: 120,
    minAge: 10,
    averageRating: 7.1,
    bayesRating: 6.9,
    usersRated: 130000,
    averageWeight: 2.3,
    numWeightVotes: 20000,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Dice Rolling', 'Trading', 'Network and Route Building'],
    categories: ['Economic', 'Negotiation'],
    playerPolls: [
      { playerCount: 3, best: 300, recommended: 900, notRecommended: 200 },
      { playerCount: 4, best: 1400, recommended: 400, notRecommended: 60 },
    ],
  },
  {
    bggId: 30549,
    name: 'Pandemic',
    yearPublished: 2008,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playingTime: 45,
    minPlayTime: 45,
    maxPlayTime: 45,
    minAge: 8,
    averageRating: 7.6,
    bayesRating: 7.4,
    usersRated: 140000,
    averageWeight: 2.4,
    numWeightVotes: 22000,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Cooperative Game', 'Hand Management', 'Point to Point Movement'],
    categories: ['Medical'],
    playerPolls: [
      { playerCount: 2, best: 400, recommended: 1100, notRecommended: 150 },
      { playerCount: 3, best: 900, recommended: 800, notRecommended: 60 },
      { playerCount: 4, best: 1200, recommended: 600, notRecommended: 80 },
    ],
  },
  {
    bggId: 39856,
    name: 'Dixit',
    yearPublished: 2008,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 3,
    maxPlayers: 6,
    playingTime: 30,
    minPlayTime: 30,
    maxPlayTime: 30,
    minAge: 8,
    averageRating: 7.3,
    bayesRating: 7.1,
    usersRated: 90000,
    averageWeight: 1.2,
    numWeightVotes: 12000,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Storytelling', 'Simultaneous Action Selection', 'Voting'],
    categories: ['Card Game', 'Party Game'],
    playerPolls: [
      { playerCount: 3, best: 40, recommended: 400, notRecommended: 700 },
      { playerCount: 4, best: 200, recommended: 900, notRecommended: 120 },
      { playerCount: 5, best: 900, recommended: 500, notRecommended: 40 },
      { playerCount: 6, best: 1100, recommended: 400, notRecommended: 40 },
    ],
  },
  {
    bggId: 167791,
    name: 'Terraforming Mars',
    yearPublished: 2016,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 1,
    maxPlayers: 5,
    playingTime: 120,
    minPlayTime: 120,
    maxPlayTime: 120,
    minAge: 12,
    averageRating: 8.3,
    bayesRating: 8.0,
    usersRated: 110000,
    averageWeight: 3.3,
    numWeightVotes: 18000,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Card Drafting', 'Tile Placement', 'Engine Building'],
    categories: ['Economic', 'Science Fiction'],
    playerPolls: [
      { playerCount: 1, best: 200, recommended: 700, notRecommended: 400 },
      { playerCount: 2, best: 500, recommended: 1200, notRecommended: 200 },
      { playerCount: 3, best: 1300, recommended: 700, notRecommended: 80 },
      { playerCount: 4, best: 700, recommended: 900, notRecommended: 200 },
      { playerCount: 5, best: 200, recommended: 700, notRecommended: 800 },
    ],
  },
  {
    bggId: 224517,
    name: 'Brass: Birmingham',
    yearPublished: 2018,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playingTime: 120,
    minPlayTime: 60,
    maxPlayTime: 120,
    minAge: 14,
    averageRating: 8.6,
    bayesRating: 8.4,
    usersRated: 55000,
    averageWeight: 3.9,
    numWeightVotes: 9000,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Network and Route Building', 'Hand Management', 'Income'],
    categories: ['Economic', 'Industry / Manufacturing'],
    playerPolls: [
      { playerCount: 2, best: 300, recommended: 900, notRecommended: 200 },
      { playerCount: 3, best: 1100, recommended: 500, notRecommended: 40 },
      { playerCount: 4, best: 900, recommended: 600, notRecommended: 60 },
    ],
  },
  {
    bggId: 178900,
    name: 'Codenames',
    yearPublished: 2015,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 2,
    maxPlayers: 8,
    playingTime: 15,
    minPlayTime: 15,
    maxPlayTime: 15,
    minAge: 14,
    averageRating: 7.6,
    bayesRating: 7.4,
    usersRated: 90000,
    averageWeight: 1.3,
    numWeightVotes: 11000,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Team-Based Game', 'Push Your Luck'],
    categories: ['Card Game', 'Party Game', 'Word Game'],
    playerPolls: [
      { playerCount: 2, best: 30, recommended: 300, notRecommended: 900 },
      { playerCount: 4, best: 500, recommended: 900, notRecommended: 100 },
      { playerCount: 6, best: 1200, recommended: 400, notRecommended: 40 },
      { playerCount: 8, best: 700, recommended: 600, notRecommended: 100 },
    ],
  },
  {
    bggId: 148228,
    name: 'Splendor',
    yearPublished: 2014,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 2,
    maxPlayers: 4,
    playingTime: 30,
    minPlayTime: 30,
    maxPlayTime: 30,
    minAge: 10,
    averageRating: 7.4,
    bayesRating: 7.1,
    usersRated: 95000,
    averageWeight: 1.8,
    numWeightVotes: 14000,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Set Collection', 'Engine Building'],
    categories: ['Card Game', 'Renaissance'],
    playerPolls: [
      { playerCount: 2, best: 700, recommended: 800, notRecommended: 150 },
      { playerCount: 3, best: 900, recommended: 700, notRecommended: 80 },
      { playerCount: 4, best: 500, recommended: 800, notRecommended: 250 },
    ],
  },
  {
    bggId: 68448,
    name: '7 Wonders',
    yearPublished: 2010,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 2,
    maxPlayers: 7,
    playingTime: 30,
    minPlayTime: 30,
    maxPlayTime: 30,
    minAge: 10,
    averageRating: 7.7,
    bayesRating: 7.6,
    usersRated: 100000,
    averageWeight: 2.3,
    numWeightVotes: 16000,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Card Drafting', 'Set Collection', 'Simultaneous Action Selection'],
    categories: ['Ancient', 'Card Game', 'City Building'],
    playerPolls: [
      { playerCount: 2, best: 20, recommended: 200, notRecommended: 1400 },
      { playerCount: 4, best: 700, recommended: 900, notRecommended: 90 },
      { playerCount: 5, best: 1000, recommended: 600, notRecommended: 60 },
      { playerCount: 6, best: 700, recommended: 700, notRecommended: 120 },
      { playerCount: 7, best: 500, recommended: 700, notRecommended: 220 },
    ],
  },
  {
    bggId: 266192,
    name: 'Wingspan',
    yearPublished: 2019,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 1,
    maxPlayers: 5,
    playingTime: 70,
    minPlayTime: 40,
    maxPlayTime: 70,
    minAge: 10,
    averageRating: 8.0,
    bayesRating: 7.8,
    usersRated: 120000,
    averageWeight: 2.4,
    numWeightVotes: 17000,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Engine Building', 'Set Collection', 'Dice Rolling'],
    categories: ['Animals', 'Card Game'],
    playerPolls: [
      { playerCount: 1, best: 400, recommended: 900, notRecommended: 300 },
      { playerCount: 2, best: 900, recommended: 800, notRecommended: 100 },
      { playerCount: 3, best: 1100, recommended: 700, notRecommended: 60 },
      { playerCount: 4, best: 700, recommended: 800, notRecommended: 200 },
      { playerCount: 5, best: 200, recommended: 600, notRecommended: 700 },
    ],
  },
  {
    bggId: 342942,
    name: 'Ark Nova',
    yearPublished: 2021,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 1,
    maxPlayers: 4,
    playingTime: 150,
    minPlayTime: 90,
    maxPlayTime: 150,
    minAge: 14,
    averageRating: 8.5,
    bayesRating: 8.3,
    usersRated: 60000,
    averageWeight: 3.8,
    numWeightVotes: 8000,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Card Drafting', 'Tile Placement', 'Engine Building'],
    categories: ['Animals', 'Economic'],
    playerPolls: [
      { playerCount: 1, best: 300, recommended: 800, notRecommended: 300 },
      { playerCount: 2, best: 1200, recommended: 600, notRecommended: 60 },
      { playerCount: 3, best: 500, recommended: 900, notRecommended: 200 },
      { playerCount: 4, best: 150, recommended: 600, notRecommended: 800 },
    ],
  },
  {
    // An expansion, to exercise the "never standalone" rule.
    bggId: 926,
    name: 'CATAN: Cities & Knights',
    yearPublished: 1998,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 3,
    maxPlayers: 4,
    playingTime: 120,
    minPlayTime: 90,
    maxPlayTime: 120,
    minAge: 12,
    averageRating: 7.4,
    bayesRating: 7.2,
    usersRated: 30000,
    averageWeight: 3.0,
    numWeightVotes: 4000,
    isExpansion: true,
    baseGameBggIds: [13],
    mechanics: ['Dice Rolling', 'Trading'],
    categories: ['Economic', 'Expansion for Base-game'],
    playerPolls: [
      { playerCount: 3, best: 300, recommended: 600, notRecommended: 100 },
      { playerCount: 4, best: 700, recommended: 300, notRecommended: 60 },
    ],
  },
  {
    // A long, heavy game: useful for exercising the hard duration limit.
    bggId: 12333,
    name: 'Twilight Struggle',
    yearPublished: 2005,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 2,
    maxPlayers: 2,
    playingTime: 180,
    minPlayTime: 120,
    maxPlayTime: 180,
    minAge: 13,
    averageRating: 8.2,
    bayesRating: 8.0,
    usersRated: 50000,
    averageWeight: 3.6,
    numWeightVotes: 7000,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Area Majority / Influence', 'Hand Management'],
    categories: ['Political', 'Wargame'],
    playerPolls: [{ playerCount: 2, best: 2000, recommended: 100, notRecommended: 20 }],
  },
  {
    // Deliberately sparse: no weight, no rating, no polls. Exercises the
    // "missing data reduces confidence" path end to end.
    bggId: 999901,
    name: 'Attic Find: Unlabelled Trick-Taker',
    yearPublished: null,
    imageUrl: null,
    thumbnailUrl: null,
    minPlayers: 3,
    maxPlayers: 5,
    playingTime: null,
    minPlayTime: null,
    maxPlayTime: null,
    minAge: null,
    averageRating: null,
    bayesRating: null,
    usersRated: null,
    averageWeight: null,
    numWeightVotes: null,
    isExpansion: false,
    baseGameBggIds: [],
    mechanics: ['Trick-taking'],
    categories: ['Card Game'],
    playerPolls: [],
  },
];
